
// This file has been generated by the GUI designer. Do not modify.
namespace Agent
{
	public partial class Login
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Entry entryName;
		private global::Gtk.Entry entryPassword;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Button LoginButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Agent.Login
			this.Name = "Agent.Login";
			this.Title = global::Mono.Unix.Catalog.GetString ("Mono Agent Login");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Agent.Login.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryName = new global::Gtk.Entry ();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.fixed1.Add (this.entryName);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryName]));
			w1.X = 107;
			w1.Y = 51;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entryPassword = new global::Gtk.Entry ();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.IsEditable = true;
			this.entryPassword.Visibility = false;
			this.entryPassword.InvisibleChar = '●';
			this.fixed1.Add (this.entryPassword);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryPassword]));
			w2.X = 107;
			w2.Y = 105;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w3.X = 58;
			w3.Y = 56;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w4.X = 41;
			w4.Y = 109;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.LoginButton = new global::Gtk.Button ();
			this.LoginButton.CanFocus = true;
			this.LoginButton.Events = ((global::Gdk.EventMask)(256));
			this.LoginButton.Name = "LoginButton";
			this.LoginButton.UseUnderline = true;
			this.LoginButton.Label = global::Mono.Unix.Catalog.GetString ("Login");
			this.fixed1.Add (this.LoginButton);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.LoginButton]));
			w5.X = 160;
			w5.Y = 147;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 367;
			this.DefaultHeight = 222;
			this.Show ();
			this.LoginButton.Clicked += new global::System.EventHandler (this.ButtonPressHandler);
		}
	}
}
